### ISSUE TITLE
BadCredentialsException

### ISSUE THREAD

**Issue by noguysland** [seLain/ghsp2ofer#12]
Got BadCredentialsException when runnng the bot...
```
Traceback (most recent call last):
  File "bot.py", line 165, in <module>
    bot.run()
  File "bot.py", line 146, in run
    root_dir=settings.DEFAULT_CLONE_ROOT_DIR)
  File "bot.py", line 47, in repo_clone
    repo = self.github.get_user().get_repo(name=repo_name)
  File "C:\ghsp2ofer\lib\site-packages\github\AuthenticatedUser.py", line 876, in get_repo
    "/repos/" + self.login + "/" + name
  File "C:\ghsp2ofer\lib\site-packages\github\AuthenticatedUser.py", line 213, in login
    self._completeIfNotSet(self._login)
  File "C:\ghsp2ofer\lib\site-packages\github\GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "C:\ghsp2ofer\lib\site-packages\github\GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "C:\ghsp2ofer\lib\site-packages\github\GithubObject.py", line 260, in __complete
    self._url.value
  File "C:\ghsp2ofer\lib\site-packages\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\ghsp2ofer\lib\site-packages\github\Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
```
Any suggestion ?

**Comment by seLain** [comment]
1. Make sure using the correct account/passwd pair
2. Could you provide exact execution steps ? (from environment setting to bot execution)
3. Have you run multiple bots on the same machine ?
4. Have you registered GitHub Desktop with another account/passwd pair ?

**Comment by noguysland** [comment]
Figured it out myself. It turns out github token must be acquired after creating my repository. Or the token will be invalid.
