### ISSUE TITLE
UnicodeDecodeError: 'cp950' codec can't decode

### ISSUE THREAD

**Issue by pczheng** [seLain/ghsp2ofer#2]
使用 settings.py    DEFAULT_COMMIT_TOOL = 'PyGithub'
執行時會遇到
```
Traceback (most recent call last):
  File "bot.py", line 147, in <module>
    bot.run()
  File "bot.py", line 134, in run
    self.random_auto_commit()
  File "bot.py", line 122, in random_auto_commit
    message=message)
  File "bot.py", line 62, in remote_addfiles_commit
    data = input_file.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xb5 in position 1794: illeg
al multibyte sequence
```
無法正確進行

**Comment by seLain** [comment]
It's a common issue reading files under Windows using python. You can google `UnicodeDecodeError`, `cp950` for various tricky solutions. Basically you have to change code page setting of terminal.

I am gonna close this issue since it's not problem of this bot.
