### ISSUE TITLE
cant not add files listed at gitignore

### ISSUE THREAD

**Issue by Pyrrhadile** [seLain/ghsp2ofer#4]
The bot try to copy file excluded in gitignore  
and exception happen

```
(ghsp2ofer) C:\ghsp2ofer-adile>python bot.py
auto commit.
Traceback (most recent call last):
  File "bot.py", line 80, in addfiles_commit_push_remote
    shutil.copy2(src, dest)
  File "c:\Python36\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'cloned_repos\\ghsp2ofer
\\locale\\sv\\LC_MESSAGES\\p1tr.mo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 147, in <module>
    bot.run()
  File "bot.py", line 134, in run
    self.random_auto_commit()
  File "bot.py", line 115, in random_auto_commit
    message=message)
  File "bot.py", line 86, in addfiles_commit_push_remote
    repo.git.add(file)
  File "C:\py36_venv\ghsp2ofer\lib\site-packages\gitpy
thon-2.1.8-py3.6.egg\git\cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\py36_venv\ghsp2ofer\lib\site-packages\gitpy
thon-2.1.8-py3.6.egg\git\cmd.py", line 1010, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\py36_venv\ghsp2ofer\lib\site-packages\gitpy
thon-2.1.8-py3.6.egg\git\cmd.py", line 821, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git add locale\sv\LC_MESSAGES\p1tr.mo
  stderr: 'The following paths are ignored by one of your .gitignore files:
locale/sv/LC_MESSAGES/p1tr.mo
Use -f if you really want to add them.'
```

**Comment by seLain** [comment]
It makes sense that what is specified in `.gitignore` should not be added for commit.  
An intuitive solution is to catch this exception and ignore this add action, or stops entire operation.  
But I'll take some time to seek for better solutions. Any suggestion is welcomed.

**Comment by seLain** [comment]
Fixed by handling exception when doing git add. 
If exception happens, the specific file will be ignored from adding into repository.
